stg_location_table = "stg_location"
stg_room_table = "stg_room"
stg_guest_table = "stg_guest"
stg_booking_table = "stg_booking"
stg_booking_room_table = "stg_booking_room"
stg_booking_addon_table = "stg_booking_addon"

dim_date_table = "dim_date"
dim_roomtype_table = "dim_roomtype"
dim_addon_table = "dim_addon"
dim_guest_table = "dim_guest"
dim_location_table = "dim_location"
fct_booking_table = "fct_booking"
fct_purchase_table = "fct_purchase"
