version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: $DB_HOST_INTERNAL
    env_file:
      - '.env'
    ports:
      - $DB_PORT:3306

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: $ZOOKEEPER_HOST_INTERNAL
    env_file:
      - '.env'
    ports:
      - $ZOOKEEPER_PORT:2181

  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: $KAFKA_HOST_INTERNAL
    env_file:
      - '.env'
    depends_on:
      - zookeeper
    ports:
      - $KAFKA_PORT_INTERNAL:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: $SCHEMA_REGISTRY_HOST_INTERNAL
    depends_on:
      - broker
    ports:
      - $REGISTRY_PORT:8081
    env_file:
      - .env

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    container_name: $CONNECT_HOST_INTERNAL
    depends_on:
      - broker
      - schema-registry
    ports:
      - $CONNECT_REST_PORT:8083
    env_file:
      - .env
    command:  
      - bash
      - -c
      - |
        echo "Installing Connector"
        curl -O https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.3.3.Final/debezium-connector-mysql-2.3.3.Final-plugin.tar.gz
        tar -xzf debezium-connector-mysql-2.3.3.Final-plugin.tar.gz -C $CONNECT_PLUGIN_PATH
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run
      

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: $KSQL_SERVER_HOST_INTERNAL
    depends_on:
      - broker
      - schema-registry
    ports:
      - $KSQL_SERVER_PORT:8088
    env_file:
      - .env

  processor:
    depends_on:
      - kafka-connect
      - mysql
    build: processors/
    image: processor
    container_name: $PROCESSORS_HOST_INTERNAL
    env_file:
      - '.env'
    command: "./run.sh"
