version: '3'
x-common:
  &airflow-env-vars
  environment:
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
services:
  zookeeper:
    image: debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - "2181:2181"

  broker:
    image: debezium/kafka:2.3
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:9092
      ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:9092

  kafka-connect:
    depends_on:
      - broker
      - mysql
    image: debezium/connect:2.3
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 'broker:9092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: 'hotel-config'
      OFFSET_STORAGE_TOPIC: 'hotel-offset'
      STATUS_STORAGE_TOPIC: 'hotel-status'

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD

  processor:
    depends_on:
      - kafka-connect
      - mysql
    build: 
      context: processors/
      dockerfile: stream/Dockerfile
    image: processor:latest
    container_name: processor
    env_file:
      - '.env'
    command: "stream/run.sh"
    volumes:
      - ./processors/stream:/processor/stream
  
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - '.env'

  airflow-init:
    build: airflow/
    image: airflow:2.3.3
    container_name: airflow-init
    env_file:
      - '.env'
    <<: *airflow-env-vars
    entrypoint: bash -c
    command: /setup.sh
    depends_on:
      - postgres

  airflow-scheduler:
    build: airflow/
    image: airflow:2.3.3
    container_name: airflow-scheduler
    command: scheduler
    env_file:
      - '.env'
    <<: *airflow-env-vars
    depends_on:
      airflow-init:
        condition: service_completed_successfully
  
  airflow-webserver:
    build: airflow/
    image: airflow:2.3.3
    container_name: airflow-webserver
    command: webserver
    env_file:
      - '.env'
    <<: *airflow-env-vars
    ports:
      - 8080:8080
    depends_on:
      - airflow-scheduler
