version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: $DB_HOST_INTERNAL
    env_file:
      - '.env'
    ports:
      - $DB_PORT:3306

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: $ZOOKEEPER_HOST_INTERNAL
    env_file:
      - '.env'
    ports:
      - $ZOOKEEPER_PORT:2181

  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: $KAFKA_HOST_INTERNAL
    env_file:
      - '.env'
    depends_on:
      - zookeeper
    ports:
      - $KAFKA_PORT_INTERNAL:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: $SCHEMA_REGISTRY_HOST_INTERNAL
    depends_on:
      - zookeeper
      - broker
    ports:
      - $SCHEMA_REGISTRY_PORT:8081
    env_file:
      - .env

  kafka-connect:
    image: kafka-connect
    build: kafka_connect/
    container_name: $CONNECT_HOST_INTERNAL
    depends_on:
      - broker
      - schema-registry
    ports:
      - $CONNECT_PORT:8083
    env_file:
      - .env

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: $KSQL_SERVER_HOST_INTERNAL
    depends_on:
      - broker
      - schema-registry
    ports:
      - $KSQL_SERVER_PORT:8088
    env_file:
      - .env

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: $KSQL_CLI_HOST_INTERNAL
    depends_on:
      - broker
      - ksqldb-server
    env_file:
      - .env
    entrypoint: /bin/sh
    tty: true
