version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - "2181:2181"

  broker:
    image: debezium/kafka:2.3
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092

  kafka-connect:
    depends_on:
      - broker
      - mysql
    image: debezium/connect:2.3
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 'broker:9092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: 'hotel-config'
      OFFSET_STORAGE_TOPIC: 'hotel-offset'
      STATUS_STORAGE_TOPIC: 'hotel-status'
      # ADVERTISED_HOST_NAME: 'kafka-connect'

  
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD

  processor:
    depends_on:
      - kafka-connect
      - mysql
    build: processors/
    image: processor:latest
    container_name: processor
    volumes:
      - ./processors:/processor
    env_file:
      - '.env'
    command: "/processor/run.sh"
