FEATURE_FLAGS = {
    "HORIZONTAL_FILTER_BAR": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_FILTERS_EXPERIMENTAL": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "DATAPANEL_CLOSED_BY_DEFAULT": True,
    "DISABLE_LEGACY_DATASOURCE_EDITOR": True,
}
